### ISSUE TITLE
Add options to changelog command to create partial changelog

### ISSUE THREAD

**Issue by mvanbaak** [raulgomis/semversioner#1]
Usecase: generate changelog for just the changes in the latest release. These can be used to create github/gitlab releases.

I was thinking about the options ```--from``` and ```--to``` where the defaults are from the start and until the end (as it is now).
But one could do: ```semversioner changelog --from $previous_version > latest-changes.md```  and use that as data for a release description

**Comment by raulgomis** [comment]
Hi @mvanbaak ,

Thanks for your suggestion. I think it's a great idea. 

Just thinking about the implementation details: is there any use case you think in which you might want a subset of the changelog? or you always want the latest release?

**Comment by mvanbaak** [comment]
For my usecase I think I can get away with the latest release.

**Comment by raulgomis** [comment]
@mvanbaak I just created a pull request #6 to support this feature request. Feedback is always welcome :)

**Comment by mvanbaak** [comment]
Thanks a lot. It does exactly what I need for my usecase.
