### ISSUE TITLE
Bug with semversioner release command

### ISSUE THREAD

**Issue by lissyaka** [raulgomis/semversioner#11]
When doing release and having .semversioner folder instead of .changes folder, semversioner release command does not work.

**Comment by raulgomis** [comment]
Hi @lissyaka ,

Can you specify the version of `semversioner` you are using? and the commands used to reproduce it?

The following set of commands work well in `0.13.0` version:
```
semversioner add-change -t minor -d "Test"
semversioner release
```

If you are using an old version of semversioner it might not have support for `.semversioner` directory (the default one now).

**Comment by lissyaka** [comment]
Steps to reproduce:

1. Fork this repo [demo pipe python](https://bitbucket.org/atlassian/demo-pipe-python/src/master/)
2. `pip install -r requirements.txt`
3. `pip install semversioner` (output: semversioner-0.13.0)
4. `semversioner add-change --type patch --description "Test."` . It creates `.semversioner/...` folder
5. Update repo with you docker image path, make some custom changes: i.e.  add`logger.info('test')` inside pipe.py in DemoPipe.run()
5. Try to push image to docker
6. In your pipeline out put you will see `✖ Error: No changes to release. Skipping release process.`

**Comment by lissyaka** [comment]
Some updates:

1. `semversioner release` works correct
2. but when it calls under subprocess:
```import subprocess

subprocess.run(['semversioner', 'release'], check=True, capture_output=True, text=True)
```
then it fails with `✖ Error: No changes to release. Skipping release process.`

**Comment by lissyaka** [comment]
I finally found the reason. This bug is not related to semversioner. The problem occurs in subprocess because wrong workdir is provided inside bitbucket-pipe-release toolkit by default. 

My suggestion is to append `path_to_search_changes` where semversioner tried to find changes additionally to this text `✖ Error: No changes to release. Skipping release process.`
