### ISSUE TITLE
Feature Request: `semversioner check` command

### ISSUE THREAD

**Issue by darthtrevino** [raulgomis/semversioner#15]
I've been using predominately JavaScript-based ecosystems, and we have similar tooling for describing changeset documents as part of an ongoing release process. The ones most analogous are [beachball](https://microsoft.github.io/beachball/) and the [Yarn Version Plugin](https://yarnpkg.com/features/release-workflow)

One thing I like about these tools is that they can help you enforce a policy where every pull request must have a change document. e.g. `beachball check`, that can be integrated into CI.

It would be very nice if semversioner had an analogous command to assert that the current branch has an change document defined.

**Comment by raulgomis** [comment]
Hi @darthtrevino ,

Thanks for your feature request and describing the use case that well. It makes sense, I'll think about it soon.

**Comment by raulgomis** [comment]
@darthtrevino this is supported from version 1.3.0. Let me know your feedback!
