### ISSUE TITLE
current date

### ISSUE THREAD

**Issue by FStefanni** [raulgomis/semversioner#16]
Hi,

in my changelog template I like to add the date on wihch I made a release, something as:
```
## {{ release.version }} - {{ release.date }}
```

expecting as output something as:
```
## 1.3.5 - 2022-08-05
```
(basically, the date in ISO format)

But it seems not possible right now.
It would be a cool feature to ad imho.

Regards

**Comment by raulgomis** [comment]
Hi @FStefanni ,

Thanks for your feature request. It makes total sense to me.

**Comment by raulgomis** [comment]
Hi everyone,

This is already supported since semversioner 1.4.0 version.

Note: It is still not included by default in the Changelog template. If you want to use it, please use this template instead:

```
# Changelog
Note: version releases in the 0.x.y range may introduce breaking changes.
{% for release in releases %}

## {{ release.version }}{{ ' (' + release.created_at.strftime("%m-%d-%Y") + ')' if release.created_at }}

{% for change in release.changes %}
- {{ change.type }}: {{ change.description }}
{% endfor %}
{% endfor %}
```

**Comment by FStefanni** [comment]
Hi,

great! I tested it and it works fine. So we can close this issue.

Thank you.
Regards
