### ISSUE TITLE
Semversioner release method calls sys.exit when used in module

### ISSUE THREAD

**Issue by oobug** [raulgomis/semversioner#18]
As a user, I would like to be able to import the semversioner library into my own Python code and use the `Semversioner.release` method without Semversioner closing my program.

The `release` function of the `semversioner.core.Semversioner` class calls `sys.exit(-1)` if no changes are found. This is appropriate when running the CLI, but requires cumbersome workarounds if used as a function within other Python code.

**Comment by oobug** [comment]
As a follow-up question for this issue, is the expectation that users of the semversioner module use the provided `release` function, or is the expectation that the underlying functionality of this function should be re-implemented in consumers' code?

**Comment by raulgomis** [comment]
Hi @oobug ! Thanks for your question. What's your use case for willing to use semversioner as a module in your Python library? Broadly speaking it makes total sense to me, I tried to modularise the code as much as I could until I could find a legit use case to understand better the API methods, etc. Also, I agree, the library API should be better handled with exceptions instead

**Comment by oobug** [comment]
Hi @raulgomis! My use case is that I'm implementing a Bitbucket Pipe that will use Semversioner, and I'm currently invoking Semversioner directly within my Python code rather than using the `subprocess` module.

My pipe is currently using the `get_last_version`, `release`, and `generate_changelog` methods of `semversioner.core.Semversioner`.

This is essentially a fork of https://bitbucket.org/atlassian/bitbucket-pipe-release/ without all of the Pipe-specific handling, just version updating.

**Comment by raulgomis** [comment]
Hi @oobug . This is supported from version 1.3.0. Let me know your feedback and thoughts!
