### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by DSchougaard** [raulgomis/semversioner#21]
During adjustments of my pull request, I noticed the following deprecation notice, running Python 3.10 on Windows:
`DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  releases = sorted(list(map(lambda x: x[:-len('.json')], files)), key=StrictVersion, reverse=True)`

It looks like a simple drop-in replacement.

**Comment by raulgomis** [comment]
Thanks for raising the issue @DSchougaard . That warning will be fixed when the following branch is integrated: https://github.com/raulgomis/semversioner/compare/master...feature/prerelease-versions. Still WIP.
