### ISSUE TITLE
Feature request: custom additional properties

### ISSUE THREAD

**Issue by FStefanni** [raulgomis/semversioner#30]
Hi,

it could be nice to be able to add custom properties, referable in the template.
An example could be (but please feel free to change as you prefer):
```
semversioner add-change --property release.maintainer="Me" --property change.restart=true property change.limit=90.4
```
This could generate something referable in the template as:
```
{{% release.maintainer %}}
{{% change.restart %}}
{{% change.limit %}}
```

This is useful to be able to embed more structured data, and to generate more complex changelogs.

For example, I have a project consisting of various components, each versioned with its own version number.
So the changelog is structured in sections, one for each component.
So I could use the custom properties to be able to put the information in the correct section (e.g. `--property change.component="my component"`).

Regards

**Comment by raulgomis** [comment]
Hi @FStefanni ,

Semversioner `2.0` already supports this use case. For example, you could do:

```
semversioner add-change --type patch --description "My custom changelog message with attributes." --attributes pr_id=322 --attributes issue_id=123
```

and create a custom changelog template as follows:

```
# Changelog
Note: version releases in the 0.x.y range may introduce breaking changes.
{% for release in releases %}

## {{ release.version }}

{% for change in release.changes %}
- {{ change.type }}: {{ change.description }}{{ ' (#' + change.attributes.pr_id + ')' if change.attributes }}{{ ' (J' + change.attributes.issue_id + ')' if change.attributes }}
{% endfor %}
{% endfor %}
```

More details in the `README.md` documentation. Feel free to give it a try and share your feedback. 

Thanks for sharing your use case and thoughts.

Regards,
Raul
