### ISSUE TITLE
Incompatible requirements introduced with v1.5.1 and packaging module.

### ISSUE THREAD

**Issue by Telltak** [raulgomis/semversioner#36]
Hi, the following PR has introduced a bug on Alpine systems as the updated dependency on `packaging >= 23.0` tries to uninstall the pre-installed version `21.3` which errors with 
`
ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

Is there scope to change the minimum version here?

Steps to reproduce:
From `alpine:latest`
`pip3 install semversioner`
See error

**Comment by raulgomis** [comment]
@Telltak , the new version should fix your incompatibility issues. Alpine doesn't install `python` `pip` so it must be related to other libraries or modules you have installed in your container. In any case, the new version should fix the issues. Thanks for the report.

**Comment by Telltak** [comment]
@raulgomis brilliant news! Thanks for looking into this so fast. We had begun pinning affected repos.

Re:alpine, my guess would be that this comes from their root fs, but that's one I'll take a deeper look at for my own knowledge!

**Comment by raulgomis** [comment]
Thanks for the report @Telltak ! 👌
