### ISSUE TITLE
Support Ignoring .gitkeep in the next-release folder

### ISSUE THREAD

**Issue by michaelhrivnak** [raulgomis/semversioner#38]
I am automating the use of semversioner in a bitbucket pipelines and part of the process involves needing the next-release folder to exist after performing a release so I need to recreate the folder and add a .gitkeep file to persist the folder when pushing back to the branch.

Because of this my automation needs to temporarily delete the .gitkeep file from the folder as semversioner breaks when the file is present and attempting to perform `semversioner next-version`

**Comment by raulgomis** [comment]
Hi @michaelhrivnak ,

Thanks for your suggestion. Would you mind elaborating on your use case? Why you need to ensure the `next-release` folder exists after the release? Any context and specifics on your automation is more than welcome.

As per design, the `next-release` folder needs to be completely erased after `semversioner release`. Having all said, we can still ignore reading non JSON files in order to make it work with previously created folders containing `.gitkeep`.

**Comment by michaelhrivnak** [comment]
Hey @raulgomis, the issue I was running in to was running `release` and then commit the results back into the repo, by deleting the folder as part of performing the release (as opposed to deleting the json files only) was causing conflicts in git. For example if there is a new incoming change to the main branch that is not going to part of the release that is happening, it will have a new file in the `next-release` folder which will conflict with the automation attempting to commit a folder delete. My work around is functional for now, but it is also possible that my workflow is not very optimal!

I'm attaching the workflow script as I have it designed it, for context.

```
set -e

PIPE_SETTING=$1

validate_input() {

    if [ "$(echo $PIPE_SETTING | grep -oP 'staging|qa|production')" = "" ]; then
        echo "Needs to be called with one of \" staging, qa, production\""
        exit 0
    fi
}

# Build the semversioner type from the previous commit message
# will look for a [major] [minor] [patch] tag in the commit message, if it is not there
# defaults to a minor version update
set_change_type() {

    # do not need a fallback as it will get the previous commit
    git log --format=%B -n 1 $BITBUCKET_COMMIT

    COMMIT_MESSAGE=$(git log --format=%B -n 1 $BITBUCKET_COMMIT)
    TEMP_TYPE=$(echo $COMMIT_MESSAGE | grep -oP '(?<=\[)(major|minor|patch)(?=\])' || echo "")
    COMMIT_TYPE=${TEMP_TYPE:-minor}
    echo "the next commit type is: $COMMIT_TYPE"
}

# note: we wrap semversioner release and next-version calls in deleting .gitkeep and recreating to prevent an error:
# active issue: https://github.com/raulgomis/semversioner/issues/38

# perform a version release
update_version() {
    rm .semversioner/next-release/.gitkeep
    semversioner release
    mkdir -p .semversioner/next-release
    touch .semversioner/next-release/.gitkeep
}

# get the next version from semversioner
next_version() {
    rm .semversioner/next-release/.gitkeep
    version=$(semversioner next-version)
    touch .semversioner/next-release/.gitkeep
    echo $version
}

# get the current semversioner version
current_version() {
    rm .semversioner/next-release/.gitkeep
    verison=$(semversioner current-version)
    touch .semversioner/next-release/.gitkeep
    echo $version
}

# output the changelong to CHANGELOG.md
generate_change_log() {
    semversioner changelog > CHANGELOG.md;
}

# overall steps to release a version
release() {
    update_version
    generate_change_log
}

validate_input

if [ "$PIPE_SETTING" = "qa" ]; then

    echo "Adding version change from last commit"

    set_change_type
    
    # format the previous commit message to be appropriate for the description
    DESCRIPTION=$(echo $COMMIT_MESSAGE | sed -e "s^\[$COMMIT_TYPE\]^""^" | sed -e "s^Approved-by:.*^""^" | xargs -0 echo -n)
    semversioner add-change -t $COMMIT_TYPE -d "$DESCRIPTION"
    
    git add .
    git commit -m "[skip ci] adding auto version for $COMMIT_TYPE change: $BITBUCKET_COMMIT"
    git fetch
    git push

    echo "Running Versioning for qa pipe"    
    TAG="$(next_version)-build.$BITBUCKET_BUILD_NUMBER"
    echo "$TAG" > current-version.txt

    git add .
    git commit -m "tagging for QA update: $TAG"
    git tag $TAG
    git push origin $TAG

elif [ "$PIPE_SETTING" = "staging" ]; then
    echo "Running Versioning for staging pipe"
    
    TAG="$(next_version)-rc.$BITBUCKET_BUILD_NUMBER"

    echo $TAG > current-version.txt
    
    git add .
    git commit -m "creating release candidate $TAG"
    git tag $TAG
    git push origin $TAG

elif [ "$PIPE_SETTING" = "production" ]; then
    echo "Running Versioning for production pipe"

    TAG=$(next_version)

    git switch -c release/$TAG

    release

    echo "$TAG" > current-version.txt
    # update the README document
    sed -i "s^## Version [0-9].[0-9].[0-9]^## Version $TAG^" README.md

    git add .
    git commit -m "releasing version $TAG"
    git tag $TAG  
    git push origin $TAG

    git checkout main
    git pull

    # try doign a ff merge for ease, but if it fails then do a proper annotated merge
    if [[ $(git merge release/$TAG --ff-only) ]]; then
        echo "ff merge successful"
        git commit --allow-empty -m "[skip ci] merging version update $TAG back into main"
    else
        echo "ff unsuccessful"
        git merge release/$TAG -m "[skip ci] merging version update $TAG back into main"
    fi

    git push origin main
fi
```

**Comment by raulgomis** [comment]
Hi @michaelhrivnak ,

Thanks for sharing more details and your automation script. If I'm not wrong, my understanding is that you have a branching model with `qa`, `staging` and `production`. I'm not totally aware of all the details, but I'd recommend generating the release with the final artifact (i.e. executing the `release` command) before _transitioning_ to all environments qa, staging, and production. Ideally, the artifact / deliverable your team tests is the final one, making staging and production just re-tags and / or ff merges. 

This might solve your conflicts you have when merging additionally created data in the production branch. In any case, this PR might also simplify your workaround #39 .

Let me know your thoughts. I can be wrong in some of my assumptions as I don't know well all the details of your setup.

**Comment by michaelhrivnak** [comment]
Thanks for the response @raulgomis, to give you a better idea of what the work flow I'm aiming for here is, I would like to only perform `semversioner release` when we intend to release to our production environment, this means that the built up changes only get captured once per release cycle. 

To further explain:

We use Main as the Development branch in our model, whenever a merge to main happens we take the commit message from that merge and add it as the appropriate change type, the updated `next-release` folder then gets pushed back up to main. In the same sequence we create a build tagged as a `build` number that builds for our QA server.

When a particular QA build is ready for a release candidate we use the tag build to then build a release candidate for our Staging environment, this gets its own `rc` based tag.

When that rc version is approved then we do a proper `release` that creates the proper version tag. After that tag is created we want to commit the updated release notes back into our Main branch so that we keep a proper up to date Main branch. However what happens here right now is there might be more changes piling up while we go through the above cycle that are new from the current release candidate build or qa build. With the deletion of the `next-release` folder happening on release that creates the conflict I mentioned above.

I guess my other question to you would be is it imperative that the folder actually be deleted on release or would it be enough to delete all the .json files in the folder? (and thus the .gitkeep file could stick around)?

Thanks for all the input/help! If this doesn't fit with your version for the software, not a problem as we do have a work around that functions. I also think that our workflow might be a little different than the norm so this might not move the needle for enough users to be worth it.

**Comment by raulgomis** [comment]
Hi @michaelhrivnak ,

Semversioner 2.0 already supports this use case. It will only delete the changeset files (i.e. json files) in the `next-release` folder. Also, the folder will be deleted **only** if empty. 

Feel free to give it a try and share your feedback. Thanks for sharing your use case and thoughts.

Regards,
Raul
