### ISSUE TITLE
Support custom changelog template

### ISSUE THREAD

**Issue by raulgomis** [raulgomis/semversioner#8]
As a semversioner user I would like to customise the changelog output so that I can display my own text or change the default format.

**Comment by mszaf** [comment]
Hi there I really appreciate the tool you've built and use it often. 
I was thinking about implementing this and was curious to how you pictured this.

Would it be enough to:

1. Check for semversioner_template.j2 file in current project
2. If exists, load this in as the template
3. Else, use the existing template variable

Let me know how this sounds to you

**Comment by raulgomis** [comment]
Hi @mszaf ,

Thanks for the feedback and ideas! Much appreciate it. As far as I can think, there are 3 different options for implementing this requirement:

## **Option 1: Convention over configuration**

As you suggested, we can check if `.semversionver/.config/semversioner_template.j2` exists and use it instead of the default template. This option is simple and requires no configuration.

## **Option 2: Semversioner configuration**
We could add a configuration file `.semversionver/.config/config.yaml` that will allow you configure the path of your template file. This option might potentially allow reuse of the template in different projects.

For example:

```
semversioner:
  template: "/my/path/semversioner_template.j2"
  # future config options
  initial_version: "0.2.0"
```

## **Option 3: Changelog command parameter**
Optionally, we could pass a parameter to the `semversioner changelog` command. For example, it would look like this:
```
semversioner changelog --template my/path/semversioner_template.j2
```
This option allows mutiple representations of the changelog for the same repository during the CI/CD process as you could have (`semversioner changelog --template my/path/template1.j2` and `semversioner changelog --template my/path/template2.j2` For example, you might want to publish a CHANGELOG.md with one format but also publish an HTML page with the release notes or Github releases.

Why you want to customise the changelog template? Which solution would fit better in your workflow? Happy to hear your thoughts and feedback.

**Comment by raulgomis** [comment]
@mszaf I just created a PR to add support for this. Feel free to share any feedback.

**Comment by mszaf** [comment]
Hey @raulgomis , Thanks for adding this. This change will be used quite a bit!
